### ISSUE TITLE
why not (>=)

### ISSUE THREAD

**Issue by UREYPRICE** [cryptographicfool/cs50#1]
https://github.com/cryptographicfool/cs50/blob/3c872296369e221a2fcb6d3cf03a09296391a099/pset1/cash/cash.c#L26

**Comment by cryptographicfool** [comment]
you are absolutely right. I resolved that in the online lab ide during submission but forgot to update here. All if/else are supposed to have 

">="

I will update the same right away. Thanks a lot for commenting.

**Comment by cryptographicfool** [comment]
Fixed it. and thanks again for bringing this up. 
Cheers!
